# Generated by Django 2.2.3 on 2019-08-28 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(verbose_name='表id')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('db_name', models.CharField(max_length=10, verbose_name='表的库名')),
                ('table_subtype', models.CharField(choices=[('rn', '埋点数据'), ('order', '订单数据'), ('report', '报表数据'), ('other', '用户及设备属性及其他')], default='other', max_length=10, verbose_name='表业务子类型')),
                ('table_type', models.CharField(default='other', max_length=10, verbose_name='表业务类型')),
                ('db_type', models.CharField(choices=[('mysql', 'Mysql数据库'), ('hive', 'Hive数据库'), ('otherdb', '其他数据库')], default='other', max_length=10, verbose_name='数据库类型')),
                ('desc', models.CharField(max_length=128, verbose_name='表的简介')),
                ('detail', tinymce.models.HTMLField(verbose_name='表的详情')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '正常'), (2, '其他异常')], default=1, verbose_name='表的状态')),
            ],
            options={
                'verbose_name': '常用表',
                'verbose_name_plural': '常用表',
                'db_table': 's_hot_tables',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='表id')),
                ('table_name', models.CharField(default=None, max_length=100, verbose_name='表名')),
                ('db_name', models.CharField(default=None, max_length=30, verbose_name='表的库名')),
                ('table_type', models.CharField(default=None, max_length=10, verbose_name='表业务类型')),
                ('db_type', models.CharField(choices=[('mysql', 'Mysql数据库'), ('hive', 'Hive数据库'), ('otherdb', '其他数据库')], default='other', max_length=10, verbose_name='数据库类型')),
                ('create_user', models.CharField(default=None, max_length=10, null=True, verbose_name='建表人')),
                ('link_type', models.CharField(choices=[('EXTERNAL_TABLE', '外部表'), ('MANAGED_TABLE', '内部表')], default=None, max_length=15, null=True, verbose_name='内外表')),
                ('desc', models.CharField(default=None, max_length=300, null=True, verbose_name='表的简介')),
                ('last_modified_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='最后一次修改时间')),
                ('last_modified_by', models.CharField(default=None, max_length=10, null=True, verbose_name='最后修改人')),
                ('hdfs_path', models.CharField(default=None, max_length=300, null=True, verbose_name='hdfs路径')),
                ('numfiles', models.IntegerField(default=None, null=True, verbose_name='文件个数')),
                ('numrows', models.IntegerField(default=None, null=True, verbose_name='总行数')),
                ('totalsize', models.CharField(default=None, max_length=50, null=True, verbose_name='hdfs文件大小')),
                ('have_part', models.SmallIntegerField(choices=[(0, '无分区'), (1, '有分区')], default=0, verbose_name='是否存储')),
                ('max_part', models.CharField(default=None, max_length=12, null=True, verbose_name='最大dt')),
                ('min_part', models.CharField(default=None, max_length=12, null=True, verbose_name='最小dt')),
            ],
            options={
                'verbose_name': '表库',
                'verbose_name_plural': '表库',
                'db_table': 's_tables',
            },
        ),
        migrations.CreateModel(
            name='TableLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(default=None, max_length=100, null=True, verbose_name='表的自定义label，以英文|分割')),
                ('table_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Tables', verbose_name='tableid')),
            ],
            options={
                'verbose_name': '表的业务类型',
                'verbose_name_plural': '表的业务类型',
                'db_table': 's_table_lable',
            },
        ),
        migrations.CreateModel(
            name='TableDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('clo_id', models.IntegerField(default=None, verbose_name='列id')),
                ('clo_name', models.CharField(default=None, max_length=50, verbose_name='列名')),
                ('field_type', models.CharField(default=None, max_length=150, null=True, verbose_name='字段类型')),
                ('level', models.SmallIntegerField(default=0, verbose_name='字段等级,默认0普通')),
                ('comment', models.CharField(default=None, max_length=600, null=True, verbose_name='表的简介')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tables', verbose_name='tableid')),
            ],
            options={
                'verbose_name': '子表详细信息',
                'verbose_name_plural': '子表详细信息',
                'db_table': 's_table_details',
            },
        ),
    ]
