# Generated by Django 2.2.3 on 2019-08-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default=None, max_length=100, verbose_name='表名')),
                ('user', models.CharField(default=None, max_length=15, verbose_name='归属用户')),
                ('for_model', models.CharField(default=None, max_length=10, verbose_name='类别')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tables', verbose_name='tableid')),
            ],
        ),
    ]
