# Generated by Django 2.1.2 on 2019-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottables',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'Mysql数据库'), ('hive', 'Hive数据库'), ('otherdb', '其他数据库')], default='other', max_length=10, verbose_name='数据库类型'),
        ),
    ]
