# Generated by Django 2.2.3 on 2019-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledetails',
            name='clo_id',
            field=models.IntegerField(default=None, verbose_name='列id'),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='clo_name',
            field=models.CharField(default=None, max_length=50, verbose_name='列名'),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='comment',
            field=models.CharField(default=None, max_length=600, verbose_name='表的简介'),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='field_type',
            field=models.CharField(default=None, max_length=150, verbose_name='字段类型'),
        ),
    ]
