# Generated by Django 2.2.3 on 2019-07-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottables',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='tabledetails',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tables', verbose_name='tableid'),
        ),
    ]
