# Generated by Django 2.2.3 on 2019-07-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190721_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(verbose_name='表id')),
                ('table_name', models.CharField(max_length=50, verbose_name='表名')),
                ('db_name', models.CharField(max_length=10, verbose_name='表的库名')),
                ('table_type', models.CharField(default='other', max_length=10, verbose_name='表业务类型')),
                ('db_type', models.CharField(choices=[('mysql', 'Mysql数据库'), ('hive', 'Hive数据库'), ('otherdb', '其他数据库')], default='other', max_length=10, verbose_name='数据库类型')),
                ('desc', models.CharField(max_length=128, verbose_name='表的简介')),
            ],
            options={
                'verbose_name': '表库',
                'verbose_name_plural': '表库',
                'db_table': 's_tables',
            },
        ),
        migrations.AlterModelTable(
            name='hottables',
            table='s_hot_tables',
        ),
    ]
