# Generated by Django 2.2.3 on 2019-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190724_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='id',
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='表id'),
        ),
    ]
