# Generated by Django 2.1.2 on 2019-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190801_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='db_name',
            field=models.CharField(max_length=30, verbose_name='表的库名'),
        ),
    ]
