# Generated by Django 2.2.3 on 2019-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190723_1426'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tables',
            table='s_all_tables',
        ),
    ]
