# Generated by Django 2.2.3 on 2019-07-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190723_1619'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tables',
            table='s_tables',
        ),
    ]
