# Generated by Django 2.2.3 on 2019-07-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190723_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
