# Generated by Django 2.2.3 on 2019-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(verbose_name='tableid')),
                ('clo_id', models.SmallIntegerField(verbose_name='列id')),
                ('clo_name', models.CharField(max_length=20, verbose_name='列名')),
                ('field_type', models.CharField(max_length=10, verbose_name='字段类型')),
                ('level', models.SmallIntegerField(default=0, verbose_name='字段等级,默认0普通')),
                ('comment', models.CharField(max_length=128, verbose_name='表的简介')),
            ],
            options={
                'verbose_name': '子表详细信息',
                'verbose_name_plural': '子表详细信息',
                'db_table': 's_table_details',
            },
        ),
    ]
