# Generated by Django 2.2.3 on 2019-07-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='is_delete',
        ),
    ]
