# Generated by Django 2.1.2 on 2019-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
